actors:
  alice:
    image_url: /images/actors/alice.png
    name: Yamane TARO
    url: 
  bob:
    image_url: /images/actors/bob.png
    name: Goh
    url: 
author: ds
description: ぽっどきゃすと
description_long: ぽっどきゃすとです。
email: podcast@daaa.fr
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: #podcastinparis
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Podcast in Paris
url: https://poscast.daaa.fr
